// ============================================
// 商品数据 �?你只需要修改这个文�?
// ============================================
// 加新商品:复制下面任何一�?{} 大括号区�?粘贴在末�?改内容�?
// 改图�?�?image 后面的链接换成你的图�?可以�?imgur.com 等免费图床上传后获取链接)�?
// 改价�?�?price 数字(美金,数字就行,不要�?$)�?
// 商品下架:删掉对应的整�?{} 区块�?
// ============================================

const PRODUCTS = [
  {
    id: "lum-011",
    name: "The Cascade Wave",
    subtitle: "13x6 HD Lace Wig | Human Hair · Deep Wave",
    price: 309,
    images: [
      'images/lum-011/main_01.webp',
      'images/lum-011/main_02.webp',
      'images/lum-011/main_03.webp',
      'images/lum-011/main_04.webp',
      'images/lum-011/main_05.webp',
    ],
    detailImages: [
      'images/lum-011/detail_01.webp',
      'images/lum-011/detail_02.webp',
      'images/lum-011/detail_03.webp',
      'images/lum-011/detail_04.webp',
      'images/lum-011/lifestyle_01.webp',
      'images/lum-011/lifestyle_02.webp',
      'images/lum-011/lifestyle_03.webp',
    ],
    description: "A deep-wave human-hair wig with a full, defined texture and transparent 13x6 lace. The longer lace area offers flexible parting, while the adjustable cap helps you refine the fit.",
    features: [
      "13x6 transparent lace with flexible parting space",
      "Human hair with a deep-wave texture",
      "Deep wave pattern - full, bouncy, well-defined",
      "Pre-plucked hairline with soft baby hairs",
      "Use a strand test and low heat when styling",
      "Adjustable cap with combs and elastic strap",
    ],
    variants: [
      { color: 'Natural Black', length: '16inch/40cm', price: 309,  inStock: true },
      { color: 'Natural Black', length: '18inch/45cm', price: 339,  inStock: true },
      { color: 'Natural Black', length: '20inch/50cm', price: 379,  inStock: true },
      { color: 'Natural Black', length: '22inch/55cm', price: 429,  inStock: true },
      { color: 'Natural Black', length: '24inch/60cm', price: 499,  inStock: true },
      { color: 'Natural Black', length: '26inch/65cm', price: 579,  inStock: true },
      { color: 'Natural Black', length: '28inch/70cm', price: 679,  inStock: true },
      { color: 'Natural Black', length: '30inch/75cm', price: 769, inStock: true },
    ],
    featured: true,
  },
  {
    id: "lum-010",
    name: "The Platinum Bob",
    subtitle: "13x4 HD Lace Bob | Human Hair · #613",
    price: 199,
    images: [
      'images/lum-010/main_01.webp',
      'images/lum-010/main_02.webp',
      'images/lum-010/main_03.webp',
      'images/lum-010/main_04.webp',
      'images/lum-010/main_05.webp',
    ],
    detailImages: [
      'images/lum-010/detail_01.webp',
      'images/lum-010/detail_02.webp',
      'images/lum-010/detail_03.webp',
      'images/lum-010/detail_04.webp',
      'images/lum-010/lifestyle_01.webp',
      'images/lum-010/lifestyle_02.webp',
      'images/lum-010/lifestyle_03.webp',
    ],
    description: "A straight #613 blonde human-hair bob with transparent 13x4 lace. Choose from four lengths and two density options for a shorter, polished silhouette.",
    features: [
      "13x4 transparent lace for front hairline placement",
      "Human hair in a #613 blonde finish",
      "Sleek bone-straight bob, chin-to-shoulder length",
      "Use a strand test and low heat when styling",
      "Available in 150% (standard) and 180% (full) density",
      "Adjustable cap with combs and elastic strap",
    ],
    variants: [
      // ── 8 inch · 齐下巴 Bob ──
      { color: '#613 Platinum · 150% Density', length: '8inch/20cm',  price: 199, inStock: true },
      { color: '#613 Platinum · 180% Density', length: '8inch/20cm',  price: 229, inStock: true },
      // ── 10 inch ──
      { color: '#613 Platinum · 150% Density', length: '10inch/25cm', price: 229, inStock: true },
      { color: '#613 Platinum · 180% Density', length: '10inch/25cm', price: 259, inStock: true },
      // ── 12 inch ──
      { color: '#613 Platinum · 150% Density', length: '12inch/30cm', price: 259, inStock: true },
      { color: '#613 Platinum · 180% Density', length: '12inch/30cm', price: 289, inStock: true },
      // ── 14 inch · 齐肩 Bob ──
      { color: '#613 Platinum · 150% Density', length: '14inch/35cm', price: 289, inStock: true },
      { color: '#613 Platinum · 180% Density', length: '14inch/35cm', price: 319, inStock: true },
    ],
    featured: true,
  },
  {
    id: "lum-009",
    name: "The Signature Straight",
    subtitle: "13x6 HD Lace Wig | Human Hair",
    price: 289,
    images: [
      'images/lum-009/main_01.webp',
      'images/lum-009/main_02.webp',
      'images/lum-009/main_03.webp',
      'images/lum-009/main_04.webp',
      'images/lum-009/main_05.webp',
    ],
    detailImages: [
      'images/lum-009/detail_01.webp',
      'images/lum-009/detail_02.webp',
      'images/lum-009/detail_03.webp',
      'images/lum-009/detail_04.webp',
      'images/lum-009/lifestyle_01.webp',
      'images/lum-009/lifestyle_02.webp',
      'images/lum-009/lifestyle_03.webp',
    ],
    description: "A straight human-hair wig with transparent 13x6 lace and flexible parting space. Available in two density options and lengths from 16 to 30 inches.",
    features: [
      "13x6 transparent lace with flexible parting space",
      "Human hair with a straight finish",
      "Pre-plucked hairline with soft baby hairs",
      "Use a strand test and low heat when styling",
      "Available in 150% (standard) and 180% (full) density",
      "Adjustable cap with combs and elastic strap",
    ],
    variants: [
      // ── 16 inch · 150% Density ──
      { color: 'Natural Black · 150% Density', length: '16inch/40cm', price: 289, inStock: true },
      { color: 'Natural Black · 180% Density', length: '16inch/40cm', price: 319, inStock: true },
      // ── 18 inch ──
      { color: 'Natural Black · 150% Density', length: '18inch/45cm', price: 319, inStock: true },
      { color: 'Natural Black · 180% Density', length: '18inch/45cm', price: 349, inStock: true },
      // ── 20 inch ──
      { color: 'Natural Black · 150% Density', length: '20inch/50cm', price: 349, inStock: true },
      { color: 'Natural Black · 180% Density', length: '20inch/50cm', price: 379, inStock: true },
      // ── 22 inch ──
      { color: 'Natural Black · 150% Density', length: '22inch/55cm', price: 389, inStock: true },
      { color: 'Natural Black · 180% Density', length: '22inch/55cm', price: 419, inStock: true },
      // ── 24 inch ──
      { color: 'Natural Black · 150% Density', length: '24inch/60cm', price: 449, inStock: true },
      { color: 'Natural Black · 180% Density', length: '24inch/60cm', price: 479, inStock: true },
      // ── 26 inch ──
      { color: 'Natural Black · 150% Density', length: '26inch/65cm', price: 539, inStock: true },
      { color: 'Natural Black · 180% Density', length: '26inch/65cm', price: 569, inStock: true },
      // ── 28 inch ──
      { color: 'Natural Black · 150% Density', length: '28inch/70cm', price: 649, inStock: true },
      { color: 'Natural Black · 180% Density', length: '28inch/70cm', price: 679, inStock: true },
      // ── 30 inch ──
      { color: 'Natural Black · 150% Density', length: '30inch/75cm', price: 729, inStock: true },
      { color: 'Natural Black · 180% Density', length: '30inch/75cm', price: 759, inStock: true },
    ],
    featured: true,
  },
  {
    id: "lum-012",
    name: "The Water Wave Bob",
    subtitle: "Short Water Wave Lace Wig | 100% Human Hair",
    price: 159,
    images: [
      'images/lum-012/main_01.webp',
      'images/lum-012/main_02.webp',
      'images/lum-012/main_03.webp',
      'images/lum-012/main_04.webp',
      'images/lum-012/main_05.webp',
    ],
    detailImages: [
      'images/lum-012/detail_01.webp',
      'images/lum-012/detail_02.webp',
      'images/lum-012/detail_03.webp',
      'images/lum-012/detail_04.webp',
      'images/lum-012/lifestyle_01.webp',
      'images/lum-012/lifestyle_02.webp',
      'images/lum-012/lifestyle_03.webp',
    ],
    description: "Soft water-wave texture in an easy short silhouette. Lightweight, face-framing, and ready for everyday wear, this human-hair bob gives natural movement with a polished finish that still feels effortless.",
    features: [
      "100% human hair with soft water-wave texture",
      "Short bob silhouette - light, easy, and face-framing",
      "Natural black finish for everyday styling",
      "Use a strand test and low heat when styling",
      "Beginner-friendly fit with natural movement",
      "Adjustable cap with combs and elastic strap",
    ],
    variants: [
      { color: 'Natural Black', length: 'Short Bob', price: 159, inStock: true },
    ],
    featured: true,
  },
  {
    id: "lum-013",
    name: "The Bouncy Curl Closure",
    subtitle: "5x5 Glueless Lace Wig | 200% Density Human Hair",
    price: 289,
    images: [
      'images/lum-013/main_01_front_hero.webp',
      'images/lum-013/main_02_3quarter_side.webp',
      'images/lum-013/main_03_back_3quarter.webp',
      'images/lum-013/main_04_lace_closeup_v2.webp',
      'images/lum-013/main_05_product_hero_chair.webp',
    ],
    detailImages: [
      'images/lum-013/detail_01_lace_closure_macro.webp',
      'images/lum-013/detail_02_bouncy_curl_macro.webp',
      'images/lum-013/detail_03_200_density_fullness.webp',
      'images/lum-013/detail_04_glueless_cap_structure.webp',
      'images/lum-013/detail_05_human_hair_quality.webp',
      'images/lum-013/detail_06_styling_triptych.webp',
      'images/lum-013/lifestyle_01_cafe_morning.webp',
      'images/lum-013/lifestyle_02_street_style.webp',
      'images/lum-013/lifestyle_03_mirror_wear_and_go.webp',
      'images/lum-013/lifestyle_04_evening_dinner.webp',
      'images/lum-013/lifestyle_05_home_comfort.webp',
      'images/lum-013/ad_01_campaign_space_v1.webp',
    ],
    description: "Soft, springy curls with a polished 5x5 closure finish. This glueless human-hair wig gives full 200% density, natural movement, and an easy wear-and-go fit for days when you want volume without fuss.",
    features: [
      "5x5 lace closure - natural parting with easy placement",
      "200% density for a full, bouncy curl finish",
      "100% human hair with soft medium-wave curl texture",
      "Glueless wear-and-go cap structure",
      "Use a strand test and low heat when styling",
      "Adjustable cap with combs and elastic strap",
    ],
    variants: [
      { color: 'Natural Black', length: '16inch/40cm', price: 289, inStock: true },
    ],
    featured: true,
  },
  {
    id: "lum-014",
    name: "The Champagne Body Wave",
    subtitle: "13x4 Lace Front Wig | #613 Blonde Body Wave Human Hair",
    price: 219,
    images: [
      'images/lum-014/01_front_hero_613_blonde_wig.webp',
      'images/lum-014/02_three_quarter_side_portrait.webp',
      'images/lum-014/03_back_three_quarter_view.webp',
      'images/lum-014/04_lace_front_closeup.webp',
      'images/lum-014/05_seated_product_hero_boucle_chair.webp',
    ],
    detailImages: [
      'images/lum-014/06_macro_middle_part_lace_detail.webp',
      'images/lum-014/07_hair_texture_hand_closeup.webp',
      'images/lum-014/08_wig_softness_shine_detail.webp',
      'images/lum-014/09_cap_construction_product_detail.webp',
      'images/lum-014/10_heat_style_hair_quality_detail.webp',
      'images/lum-014/11_styling_guide_triptych.webp',
      'images/lum-014/12_cafe_lifestyle.webp',
      'images/lum-014/13_street_style_lifestyle.webp',
      'images/lum-014/14_mirror_wear_and_go_lifestyle.webp',
      'images/lum-014/15_evening_restaurant_lifestyle.webp',
      'images/lum-014/16_home_sofa_lifestyle.webp',
      'images/lum-014/17_campaign_negative_space.webp',
    ],
    description: "A luminous #613 blonde body-wave wig with soft movement and a polished lace-front finish. Airy, bright, and easy to style, it brings a champagne-blonde glow without losing the natural softness of human hair.",
    features: [
      "13x4 lace front for a clean, natural hairline",
      "#613 blonde body wave - soft, luminous, and dimensional",
      "100% human hair with natural shine and movement",
      "Pre-styled body wave texture, ready to wear",
      "Use a strand test and low heat when styling",
      "Adjustable cap with combs and elastic strap",
    ],
    variants: [
      { color: '#613 Blonde Body Wave', length: '8inch/20cm', price: 219, inStock: true },
      { color: '#613 Blonde Body Wave', length: '10inch/25cm', price: 229, inStock: true },
      { color: '#613 Blonde Body Wave', length: '12inch/30cm', price: 239, inStock: true },
      { color: '#613 Blonde Body Wave', length: '14inch/35cm', price: 259, inStock: true },
    ],
    featured: true,
  },
  {
    id: "lum-015",
    name: "The Honey Noir Straight",
    subtitle: "13x4 Transparent Lace Wig | 1B/27 Highlight Human Hair",
    price: 349,
    images: [
      'images/lum-015/main_01_front_hero.webp',
      'images/lum-015/main_02_3-4_side.webp',
      'images/lum-015/main_03_back_3-4_length.webp',
      'images/lum-015/main_04_lace_hairline_closeup.webp',
      'images/lum-015/main_05_seated_product_hero.webp',
    ],
    detailImages: [
      'images/lum-015/detail_01_lace_part_macro.webp',
      'images/lum-015/detail_02_hair_texture_macro.webp',
      'images/lum-015/detail_03_color_blend_density.webp',
      'images/lum-015/detail_04_cap_structure_lace_front.webp',
      'images/lum-015/detail_05_heat_style_quality.webp',
      'images/lum-015/lifestyle_01_cafe_morning.webp',
      'images/lum-015/lifestyle_02_street_style.webp',
      'images/lum-015/lifestyle_03_mirror_routine.webp',
      'images/lum-015/lifestyle_04_evening_restaurant.webp',
      'images/lum-015/lifestyle_05_home_sofa.webp',
    ],
    description: "A sleek 1B/27 highlight lace-front wig with honey-blonde ribbons through a natural noir base. Smooth, glossy, and face-brightening, it gives everyday polish with a warmer, dimensional finish.",
    features: [
      "13x4 transparent lace front for a clean hairline",
      "1B/27 highlight blend - natural black with honey blonde dimension",
      "100% human hair with a sleek straight finish",
      "Pre-plucked look with soft movement through the lengths",
      "Use a strand test and low heat when styling",
      "Adjustable cap with combs and elastic strap",
    ],
    variants: [
      { color: '1B/27 Honey Noir', length: '18inch/45cm', price: 349, inStock: true },
      { color: '1B/27 Honey Noir', length: '20inch/50cm', price: 449, inStock: true },
      { color: '1B/27 Honey Noir', length: '22inch/55cm', price: 529, inStock: true },
      { color: '1B/27 Honey Noir', length: '24inch/60cm', price: 589, inStock: true },
    ],
    featured: true,
  },
  {
    id: "lum-016",
    name: "The Burgundy Bob Closure",
    subtitle: "5x5 Lace Bob Wig | Burgundy Bone-Straight Human Hair",
    price: 199,
    images: [
      'images/lum-016/a_high_resolution_studio_lit_fashion_beauty_port.webp',
      'images/lum-016/a_high_end_beauty_portrait_in_a_studio_a_close_up.webp',
      'images/lum-016/a_clean_studio_portrait_scene_with_a_warm_beige_ta.webp',
      'images/lum-016/a_warm_studio_portrait_scene_with_a_neutral_beige.webp',
      'images/lum-016/studio_portrait_scene_with_a_warm_beige_tan_backgr.webp',
    ],
    detailImages: [
      'images/lum-016/a_clean_high_end_beauty_product_photography_close.webp',
      'images/lum-016/a_close_up_beauty_portrait_product_style_photogr.webp',
      'images/lum-016/close_up_macro_beauty_photograph_of_glossy_black_d.webp',
      'images/lum-016/a_warm_softly_lit_indoor_portrait_beauty_shot_a.webp',
      'images/lum-016/a_warm_softly_lit_indoor_scene_a_young_adult_wom.webp',
      'images/lum-016/indoor_cafe_scene_warm_natural_light_shallow_dep.webp',
      'images/lum-016/indoor_lifestyle_portrait_scene_a_warm_softly_li.webp',
      'images/lum-016/street_portrait_scene_in_warm_golden_hour_light_a.webp',
    ],
    description: "A polished burgundy bob with a clean 5x5 closure and silky bone-straight finish. Short, glossy, and easy to wear, it gives a rich wine-red statement without losing everyday softness.",
    features: [
      "5x5 lace closure for natural parting and easy placement",
      "Burgundy wine-red bob with a sleek straight finish",
      "100% human hair with smooth shine and movement",
      "Short bob silhouette - light, polished, and face-framing",
      "Use a strand test and low heat when styling",
      "Adjustable cap with combs and elastic strap",
    ],
    variants: [
      { color: 'Burgundy Wine', length: '8inch/20cm', price: 199, inStock: true },
      { color: 'Burgundy Wine', length: '10inch/25cm', price: 239, inStock: true },
      { color: 'Burgundy Wine', length: '12inch/30cm', price: 259, inStock: true },
      { color: 'Burgundy Wine', length: '14inch/35cm', price: 289, inStock: true },
      { color: 'Burgundy Wine', length: '16inch/40cm', price: 319, inStock: true },
    ],
    featured: true,
  }
];
